name: Run Spotify Rest API Tests and Publish Reports
on:
  push:
    branches:
      - master
      - fixworkflow

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GROUPS: "smoke"
      THREAD_COUNT: "10"
      TEST_ENVIRONMENT: "qa"
      REFRESH_TOKEN: "AQAKpBvyizsZUA4s0t96F5x8kuUck8psjTK-IqHUdJXsziS6w8MRTzN1d2tZeRLrDyXAO_2zE5TkNxvwmv7GoKSJjES8o0VqaOPsWx_XmWM5quUGdG_LUrmPF3Q7bXZPk1I"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'zulu'
        cache: 'maven'

    - name: Run tests with Maven
      run: |
        mvn clean test -Dgroups="${GROUPS}" -DthreadCount="${THREAD_COUNT}" -DTEST_ENVIRONMENT="${TEST_ENVIRONMENT}" -DREFRESH_TOKEN="${REFRESH_TOKEN}"

    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20


    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
